/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/ops/cancellations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cancelled matches (panel #05 Cancelamentos) */
        get: operations["ops-list-cancellations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/court-holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually block a court slot (panel #07 write) */
        post: operations["ops-block-court-slot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/court-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List court availability issues (panel #07 Quadras Indisponíveis) */
        get: operations["ops-list-court-issues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/open-invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List open guest invites awaiting response (panel #03 Convites em Aberto) */
        get: operations["ops-list-open-invites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/payment-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List PIX bookings with pending/rejected payments (panel #06 Problemas de Pagamento) */
        get: operations["ops-list-payment-issues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/player-evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every player's received ratings + who rated them (panel #08 Avaliações Entre Jogadores) */
        get: operations["ops-list-player-evaluations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List feed post reports (panel #09 Denúncias) */
        get: operations["ops-list-reports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a feed post report status (panel #09 write) */
        patch: operations["ops-update-report-status"];
        trace?: never;
    };
    "/v1/ops/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global staff search: players by name/username (pg_trgm), or a pasted UUID resolved as a user id / booking id
         * @description Returns a discriminated result list (kind = user | booking). No `total`: user-service SearchUsers is keyset-paginated with no COUNT behind it, so only `has_more` is real.
         */
        get: operations["ops-search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/upcoming-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List confirmed upcoming matches (panel #01 Aguardando Jogo) */
        get: operations["ops-list-upcoming-matches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One player's full operational dossier: account, profile, bookings, career roll-ups, ratings received
         * @description Fans out in parallel over user-service (GetByID + GetPublicProfile) and booking-service (ListBookings + AdminListPlayerEvaluations). `stats` is omitted when the booking history exceeds the 100-row fetch cap, because the roll-ups would then be a lower bound rather than a count.
         */
        get: operations["ops-get-user-dossier"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AffectedBookingItem: {
            booking_id: string;
            /** Format: date-time */
            ends_at: string;
            guest?: components["schemas"]["OpsUserRef"];
            host: components["schemas"]["OpsUserRef"];
            /** Format: date-time */
            starts_at: string;
        };
        BlockCourtSlotRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BlockCourtSlotRequestBody.json
             */
            readonly $schema?: string;
            court_id: string;
            /** Format: date-time */
            ends_at: string;
            reason: string;
            /** Format: date-time */
            starts_at: string;
        };
        BlockCourtSlotResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BlockCourtSlotResponseBody.json
             */
            readonly $schema?: string;
            court_id: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: date-time */
            starts_at: string;
            status: string;
        };
        CancellationItem: {
            booking_id: string;
            cancel_reason: string;
            /** Format: date-time */
            cancelled_at?: string;
            court_label: string;
            guest?: components["schemas"]["OpsUserRef"];
            host: components["schemas"]["OpsUserRef"];
            /** Format: double */
            hours_before?: number;
            /** @description Booking mode: casual | ranked | quick | social | event */
            match_type?: string;
            /** Format: date-time */
            starts_at: string;
            within_policy?: boolean;
        };
        CancellationsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CancellationsResponseBody.json
             */
            readonly $schema?: string;
            cancellations: components["schemas"]["CancellationItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        CourtIssueItem: {
            affected_bookings: components["schemas"]["AffectedBookingItem"][] | null;
            /** @description Reason the founder typed when blocking the slot; absent for sync-pushed blocks (nobody typed one) */
            block_reason?: string;
            court_id: string;
            court_name: string;
            manual: boolean;
            /** Format: date-time */
            slot_end: string;
            /** Format: date-time */
            slot_start: string;
            status: string;
            street_address: string;
        };
        CourtIssuesResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CourtIssuesResponseBody.json
             */
            readonly $schema?: string;
            issues: components["schemas"]["CourtIssueItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        OpenInviteItem: {
            /** @description UUIDv7 booking identifier */
            booking_id: string;
            /** @description Human-readable court/venue label (court_name, else private-court bairro/rua) */
            court_label: string;
            /**
             * Format: date-time
             * @description When the invite/booking was created (RFC3339)
             */
            created_at: string;
            /** @description ISO 4217 currency code (BRL) */
            currency?: string;
            /**
             * Format: date-time
             * @description Invite expiry = created_at + 2h (RFC3339); computed, not stored
             */
            expires_at: string;
            /** @description Invited guest awaiting response */
            guest: components["schemas"]["OpsUserRef"];
            /** @description Whether the guest settled their half; absent when there is no guest */
            guest_payment?: components["schemas"]["PaymentLeg"];
            /** @description Booking host/proposer who sent the invite */
            host: components["schemas"]["OpsUserRef"];
            /** @description Whether the host settled their half, and how much */
            host_payment: components["schemas"]["PaymentLeg"];
            /** @description Booking mode: casual | ranked | quick | social | event */
            match_type?: string;
            /**
             * Format: int64
             * @description Booking total in centavos; 0 for a free (public-court) booking
             */
            price_cents: number;
            /**
             * Format: date-time
             * @description Slot start time (RFC3339)
             */
            starts_at: string;
        };
        OpenInvitesResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OpenInvitesResponseBody.json
             */
            readonly $schema?: string;
            invites: components["schemas"]["OpenInviteItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        OpsDossierAccount: {
            /**
             * Format: date-time
             * @description Account creation (RFC3339)
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Soft-delete timestamp; present only when status = soft_deleted
             */
            deleted_at?: string;
            /** @description Account email (users.email); staff-only contact field */
            email?: string;
            /** @description Login phone in E.164 (users.phone_e164); staff-only contact field */
            phone_e164?: string;
            /** @description Canonical role string (e.g. consumer, staff:admin) */
            role?: string;
            /** @description active | soft_deleted | anonymized | hard_deleted | unspecified (row exists but is_active = false) */
            status: string;
        };
        OpsDossierBooking: {
            booking_id: string;
            /** @description Free-text user reason, or a system literal (guest_no_show_refund | unpaid_host_timeout). It does NOT say WHO cancelled — bookings has no cancelled_by column. */
            cancel_reason?: string;
            /** Format: date-time */
            cancelled_at?: string;
            court_label: string;
            /** Format: date-time */
            created_at?: string;
            currency?: string;
            /**
             * Format: double
             * @description Hours between the cancellation and the slot; absent when cancelled_at is unset
             */
            hours_before?: number;
            /** @description The other player; absent while the booking has no guest */
            opponent?: components["schemas"]["OpsUserRef"];
            /** @description Booking-level charge outcome; empty on legacy rows */
            payment_status?: string;
            /**
             * Format: date-time
             * @description Set by MarkPlayed; absent when the match was never played
             */
            played_at?: string;
            /**
             * Format: int64
             * @description Booking total in centavos; 0 = free (public court) booking
             */
            price_cents: number;
            /**
             * @description Which side of the booking this player is on
             * @enum {string}
             */
            role: "host" | "guest";
            /** Format: date-time */
            starts_at?: string;
            /** @description Booking lifecycle status */
            status: string;
            /** @description This player's payment leg (host_has_paid/host_paid, or guest_has_paid/guest_paid) */
            their_leg: components["schemas"]["PaymentLeg"];
        };
        OpsDossierProfile: {
            bio?: string;
            /** @description Skill category A|B|C|D|PRO; empty until nivelamento */
            category?: string;
            /** @description Self-declared category at onboarding */
            category_declared?: string;
            city?: string;
            /** Format: date-time */
            created_at?: string;
            /** @description profiles.display_name; empty when onboarding never completed */
            display_name?: string;
            neighborhood?: string;
            /** @description casual | ranked */
            play_style?: string;
            /** @description True when the player hosts on their own private court */
            plays_at_home: boolean;
            /** @description tennis | padel | beach_tennis */
            sport?: string;
            state?: string;
            verified_badges?: string[] | null;
            /**
             * Format: int32
             * @description Gamification level (profiles.xp_level)
             */
            xp_level?: number;
        };
        OpsDossierRatings: {
            /**
             * Format: double
             * @description Mean of the ratings received; absent when count = 0
             */
            avg_rating?: number;
            /**
             * Format: int32
             * @description Number of ratings this player received
             */
            count: number;
            /** @description Each individual rating with its author, newest first */
            ratings: components["schemas"]["PlayerRatingItem"][] | null;
        };
        OpsDossierStats: {
            /** Format: int32 */
            as_guest: number;
            /** Format: int32 */
            as_host: number;
            /**
             * Format: int32
             * @description Every booking this player is on (host + guest), complete
             */
            bookings_total: number;
            /**
             * Format: int32
             * @description Cancelled bookings this player was on — by EITHER side or the system; not attributable (no cancelled_by column)
             */
            cancelled: number;
            /**
             * Format: int32
             * @description Cancelled bookings with no cancelled_at — the lead time cannot be computed, so they are NOT in cancelled_within_48h
             */
            cancelled_lead_time_unknown: number;
            /**
             * Format: int32
             * @description Of those, cancelled less than 48h before the slot (the beta policy window). Again not attributable to a side.
             */
            cancelled_within_48h: number;
            /**
             * Format: int32
             * @description Bookings with played_at set (MarkPlayed ran)
             */
            matches_played: number;
            /**
             * Format: int32
             * @description Bookings in status no_show
             */
            no_shows: number;
            /**
             * Format: int32
             * @description Live (non-cancelled, non-refunded) paid bookings where THIS player's leg is still unsettled
             */
            unpaid_legs: number;
        };
        OpsSearchBooking: {
            /** @description UUIDv7 booking identifier */
            booking_id: string;
            /** @description Human-readable court/venue label */
            court_label: string;
            /** @description ISO 4217 currency code (BRL) */
            currency?: string;
            /** @description Invited/confirmed guest; absent when the booking has none */
            guest?: components["schemas"]["OpsUserRef"];
            /** @description Booking host; name joined from user-service */
            host: components["schemas"]["OpsUserRef"];
            /** @description PIX/card payment outcome; empty on legacy rows */
            payment_status?: string;
            /**
             * Format: int64
             * @description Booking total in centavos; 0 for a free booking
             */
            price_cents: number;
            /**
             * Format: date-time
             * @description Slot start (RFC3339)
             */
            starts_at?: string;
            /** @description Booking lifecycle status */
            status: string;
        };
        OpsSearchResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OpsSearchResponseBody.json
             */
            readonly $schema?: string;
            /** @description True when user-service has further pages for this query. Always false for a UUID lookup. */
            has_more: boolean;
            /** @description The (trimmed) query that was executed */
            query: string;
            results: components["schemas"]["OpsSearchResult"][] | null;
        };
        OpsSearchResult: {
            booking?: components["schemas"]["OpsSearchBooking"];
            /**
             * @description Which payload is populated
             * @enum {string}
             */
            kind: "user" | "booking";
            /**
             * @description How the row was matched
             * @enum {string}
             */
            matched_by: "trgm_search" | "user_id" | "booking_id";
            user?: components["schemas"]["OpsSearchUser"];
        };
        OpsSearchUser: {
            /**
             * Format: date-time
             * @description When the account was created (RFC3339)
             */
            created_at?: string;
            /** @description Display name resolved from user-service (display_name, else @username, else short id) */
            name: string;
            /** @description Account status: active | soft_deleted | anonymized | hard_deleted | unspecified (inactive) */
            status?: string;
            /** @description UUIDv7 of the user */
            user_id: string;
            /** @description users.username; absent when the player never set one */
            username?: string;
        };
        OpsUserDossierResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OpsUserDossierResponseBody.json
             */
            readonly $schema?: string;
            account: components["schemas"]["OpsDossierAccount"];
            /** @description Their bookings (host + guest side), newest slot first */
            bookings: components["schemas"]["OpsDossierBooking"][] | null;
            /** @description True when the booking list hit the 100-row cap and is therefore incomplete */
            bookings_truncated: boolean;
            /** @description Absent when the user row exists but no profile row does (onboarding abandoned) */
            profile?: components["schemas"]["OpsDossierProfile"];
            ratings_received: components["schemas"]["OpsDossierRatings"];
            stats?: components["schemas"]["OpsDossierStats"];
            /** @description Why stats is absent, when it is */
            stats_unavailable_reason?: string;
            /** @description The player, with the same resolved-name discipline as every other panel */
            user: components["schemas"]["OpsUserRef"];
        };
        OpsUserRef: {
            /** @description Account email (users.email); staff-only, only on contact-enriched panels */
            email?: string;
            /** @description Display name resolved from user-service (profiles.display_name) */
            name: string;
            /** @description Login phone E.164 (users.phone_e164); staff-only, empty until PhoneSync backfills it */
            phone?: string;
            /** @description UUIDv7 of the user */
            user_id: string;
        };
        PaymentIssueItem: {
            /**
             * Format: int64
             * @description Charged amount in centavos (booking total_cents)
             */
            amount_cents: number;
            /** @description UUIDv7 booking identifier */
            booking_id: string;
            /** @description Booking lifecycle status at the time of the issue */
            booking_status: string;
            /**
             * Format: date-time
             * @description When the booking was created (RFC3339)
             */
            created_at: string;
            /** @description ISO 4217 currency code (BRL) */
            currency: string;
            /** @description PIX payment outcome: pending | rejected */
            payment_status: string;
            /** @description The payer (booking host); name joined from user-service on user_id */
            user: components["schemas"]["OpsUserRef"];
        };
        PaymentIssuesResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PaymentIssuesResponseBody.json
             */
            readonly $schema?: string;
            issues: components["schemas"]["PaymentIssueItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        PaymentLeg: {
            /** Format: int64 */
            amount_cents: number;
            currency?: string;
            paid: boolean;
        };
        PlayerEvaluationItem: {
            /**
             * Format: double
             * @description Mean of all ratings this player received (0 when none)
             */
            avg_rating: number;
            /**
             * Format: int32
             * @description Number of ratings this player received
             */
            count: number;
            /** @description The rated player; name joined from user-service */
            player: components["schemas"]["OpsUserRef"];
            /** @description Each individual rating with its author, newest first */
            ratings: components["schemas"]["PlayerRatingItem"][] | null;
        };
        PlayerEvaluationsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PlayerEvaluationsResponseBody.json
             */
            readonly $schema?: string;
            players: components["schemas"]["PlayerEvaluationItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        PlayerRatingItem: {
            /** @description The player who left this rating */
            author: components["schemas"]["OpsUserRef"];
            /** @description Optional free-text comment */
            comment?: string;
            /**
             * Format: date-time
             * @description When the rating was left (RFC3339)
             */
            created_at: string;
            /**
             * Format: int32
             * @description Overall rating 1..5
             */
            rating: number;
            /** @description Preset tags (e.g. court_quality:8, opponent_level:same, opponent_conduct:9) */
            tags?: string[] | null;
        };
        PostReportItem: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PostReportItem.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            details: string;
            post_id: string;
            reason: string;
            report_id: string;
            reported_user: components["schemas"]["OpsUserRef"];
            reporter: components["schemas"]["OpsUserRef"];
            /** Format: date-time */
            resolved_at?: string;
            resolved_by?: string;
            status: string;
        };
        ReportsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReportsResponseBody.json
             */
            readonly $schema?: string;
            reports: components["schemas"]["PostReportItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        UpcomingMatchItem: {
            alerts?: string[] | null;
            booking_id: string;
            court_label: string;
            /** Format: date-time */
            created_at: string;
            currency?: string;
            /** Format: date-time */
            ends_at: string;
            guest?: components["schemas"]["OpsUserRef"];
            guest_payment?: components["schemas"]["PaymentLeg"];
            host: components["schemas"]["OpsUserRef"];
            host_payment: components["schemas"]["PaymentLeg"];
            /** @description Booking mode: casual | ranked | quick | social | event */
            match_type?: string;
            payment_settled: boolean;
            payment_status?: string;
            /** Format: int64 */
            price_cents: number;
            /** Format: date-time */
            starts_at: string;
        };
        UpcomingMatchesResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpcomingMatchesResponseBody.json
             */
            readonly $schema?: string;
            matches: components["schemas"]["UpcomingMatchItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        UpdateReportStatusRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateReportStatusRequestBody.json
             */
            readonly $schema?: string;
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "ops-list-cancellations": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancellationsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-block-court-slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BlockCourtSlotRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockCourtSlotResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-court-issues": {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourtIssuesResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-open-invites": {
        parameters: {
            query?: {
                /** @description Max rows to return */
                limit?: number;
                /** @description Rows to skip (paging) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenInvitesResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-payment-issues": {
        parameters: {
            query?: {
                /** @description Max rows to return */
                limit?: number;
                /** @description Rows to skip (paging) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIssuesResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-player-evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerEvaluationsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-reports": {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-update-report-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateReportStatusRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostReportItem"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-search": {
        parameters: {
            query: {
                /** @description Free-text query (pg_trgm over display_name + username), or a UUID to resolve as a user id / booking id */
                q: string;
                /** @description Max player hits to return (user-service clamps at 50). Ignored for a UUID lookup. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsSearchResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-upcoming-matches": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingMatchesResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-get-user-dossier": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the player */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsUserDossierResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
