/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/ops/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Broadcast a push + inbox announcement to a saved audience (or all PlayTennis members)
         * @description Resolves the target member set: audience_id fans out via user-service ListUsersByAudience; an empty audience_id falls back to every PlayTennis member (ListUsersByPreferredClubBrand(brand=playtennis)) for backward compatibility. Dispatches a push + inbox notification per member via notifications-service Send with a bounded worker pool. Best-effort per recipient: a single Send failure is counted, never aborting the broadcast. Returns sent/failed/total. Staff-gated like the other /v1/ops/* write endpoints.
         */
        post: operations["ops-send-announcement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/audiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List saved announcement audiences (panel #13 targeting picker)
         * @description Fetches the saved audience filters from user-service ListAudiences, ordered presets-first then by name. `include_deleted` toggles soft-deleted rows. Staff-gated.
         */
        get: operations["ops-list-audiences"];
        put?: never;
        /**
         * Create a saved announcement audience (panel #13 write)
         * @description Persists a new audience filter (name + classes/genders/club_brand) via user-service CreateAudience. is_preset is always false for API-created audiences. Staff-gated.
         */
        post: operations["ops-create-audience"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/audiences/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Live member-count preview for a saved or inline audience filter (panel #13)
         * @description Returns the live reach of a filter via user-service CountAudienceMembers: pass audience_id to count a saved audience, or inline classes/genders/club_brand to preview an unsaved filter (the debounced call the UI makes while building a filter). Reports matched + missing_category. Staff-gated.
         */
        post: operations["ops-count-audience-members"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/audiences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a saved announcement audience (panel #13 write)
         * @description Replaces the name and filter dimensions of an existing audience via user-service UpdateAudience. Staff-gated.
         */
        put: operations["ops-update-audience"];
        post?: never;
        /**
         * Soft-delete a saved announcement audience (panel #13 write)
         * @description Soft-deletes an audience (stamps deleted_at) via user-service DeleteAudience. Preset audiences cannot be deleted — the call returns 400. Staff-gated.
         */
        delete: operations["ops-delete-audience"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/cancellations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cancelled matches (panel #05 Cancelamentos) */
        get: operations["ops-list-cancellations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/clubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search clubs by name for the audience-builder multi-select
         * @description Case-insensitive substring filter over club name, sorted by name. Backed by booking-service ListClubs (no server-side query — the ~184-club fleet is pulled once and filtered in the BFF). Returns id/name/brand/neighborhood; `id` is the value audience club_ids expects. Staff-gated.
         */
        get: operations["ops-search-clubs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/court-holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually block a court slot (panel #07 write) */
        post: operations["ops-block-court-slot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/court-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List court availability issues (panel #07 Quadras Indisponíveis) */
        get: operations["ops-list-court-issues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/courts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all courts with franchise info and slot totals */
        get: operations["ops-list-courts"];
        put?: never;
        /**
         * Create a court with pre-generated availability slots (ADR-0063 pricing)
         * @description Inserts the court then generates hourly slots for the requested horizon (default 90 days). Pricing: public courts → free; paid courts 10h–17h59 → R$220; 06h–09h59 and 18h+ → R$280.
         */
        post: operations["ops-create-court"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/courts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Hard-delete a court and all its availability slots */
        delete: operations["ops-delete-court"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/finished-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List played matches, most recent first (panel #02 Finalizadas) */
        get: operations["ops-list-finished-matches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/franchises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookable franchises (partner + public; excludes listing-only venues) */
        get: operations["ops-list-franchises"];
        put?: never;
        /** Create a new franchise */
        post: operations["ops-create-franchise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/manual-reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List paid confirmed bookings ops must physically reserve on the club side (panel #02 Reservas Manuais) */
        get: operations["ops-list-manual-reservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/open-invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List open guest invites awaiting response (panel #03 Convites em Aberto) */
        get: operations["ops-list-open-invites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/payment-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List PIX bookings with pending/rejected payments (panel #06 Problemas de Pagamento) */
        get: operations["ops-list-payment-issues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/player-evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every player's received ratings + who rated them (panel #08 Avaliações Entre Jogadores) */
        get: operations["ops-list-player-evaluations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all posts across every author (backoffice content console)
         * @description Cross-author list from feed-service AdminListPosts. Keyset-paginated newest-first; `q` searches caption; `include_deleted` toggles soft-deleted rows. Author display identities are joined best-effort from user-service. `reported` is true when an open (pending/reviewing) report targets the post.
         */
        get: operations["ops-list-posts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Soft-delete a post (staff override, audited)
         * @description Staff soft-delete: feed-service AdminDeletePost sets deleted_at (never a hard delete) and writes an append-only ops_audit_log row stamped with the acting staff principal. Requires an authenticated staff identity — the same gate the other write ops endpoints use.
         */
        delete: operations["ops-delete-post"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List feed post reports (panel #09 Denúncias) */
        get: operations["ops-list-reports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a feed post report status (panel #09 write) */
        patch: operations["ops-update-report-status"];
        trace?: never;
    };
    "/v1/ops/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global staff search: players by name/username (pg_trgm), or a pasted UUID resolved as a user id / booking id
         * @description Returns a discriminated result list (kind = user | booking). No `total`: user-service SearchUsers is keyset-paginated with no COUNT behind it, so only `has_more` is real.
         */
        get: operations["ops-search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/upcoming-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List confirmed upcoming matches (panel #01 Aguardando Jogo) */
        get: operations["ops-list-upcoming-matches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all users (backoffice user console)
         * @description Cross-user list from user-service AdminListUsers (users LEFT JOIN profiles in one query). Keyset-paginated newest-first; `q` filters over name/username/email/phone. No `total` (keyset, no COUNT). posts_count/bookings_count are best-effort 0 — no cheap per-user count RPC exists.
         */
        get: operations["ops-list-users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One player's full operational dossier: account, profile, bookings, career roll-ups, ratings received
         * @description Fans out in parallel over user-service (GetByID + GetPublicProfile) and booking-service (ListBookings + AdminListPlayerEvaluations). `stats` is omitted when the booking history exceeds the 100-row fetch cap, because the roll-ups would then be a lower bound rather than a count.
         */
        get: operations["ops-get-user-dossier"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AffectedBookingItem: {
            booking_id: string;
            /** Format: date-time */
            ends_at: string;
            guest?: components["schemas"]["OpsUserRef"];
            host: components["schemas"]["OpsUserRef"];
            /** Format: date-time */
            starts_at: string;
        };
        AudienceBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AudienceBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int32
             * @description Inclusive upper age bound in years; absent = no upper bound
             */
            age_max?: number;
            /**
             * Format: int32
             * @description Inclusive lower age bound in years; absent = no lower bound
             */
            age_min?: number;
            /**
             * Format: double
             * @description Geo-radius center latitude (WGS84); zero = no geo filter
             */
            center_lat?: number;
            /**
             * Format: double
             * @description Geo-radius center longitude (WGS84); zero = no geo filter
             */
            center_lng?: number;
            /** @description City names to include (multi); empty = any city */
            cities?: string[] | null;
            /** @description category_skill values to include (A | B | C | D | PRO); empty = any class */
            classes?: string[] | null;
            /** @description Franchise brand scope (e.g. playtennis); empty = any club */
            club_brand?: string;
            /** @description UUIDv7 club ids to scope to (multi); empty = any club */
            club_ids?: string[] | null;
            /**
             * Format: date-time
             * @description Creation timestamp (RFC3339)
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Soft-delete timestamp (RFC3339); present only for soft-deleted audiences
             */
            deleted_at?: string;
            /** @description user_gender values to include (male | female | non_binary | prefer_not_say); empty = any gender */
            genders?: string[] | null;
            /** @description UUIDv7 audience identifier */
            id: string;
            /** @description intent_kind values to include (sport | networking | friendship); empty = any intent */
            intents?: string[] | null;
            /** @description True for seeded system presets; presets cannot be deleted */
            is_preset: boolean;
            /** @description Human-readable audience name shown in the picker */
            name: string;
            /** @description Neighborhood names to include (multi); empty = any neighborhood */
            neighborhoods?: string[] | null;
            /** @description play_style values to include (casual | ranked); empty = any play style */
            play_styles?: string[] | null;
            /** @description Preferred weekdays (0=Sunday .. 6=Saturday); empty = any day */
            preferred_days?: number[] | null;
            /** @description period_of_day values to include (morning | afternoon | evening); empty = any period */
            preferred_periods?: string[] | null;
            /**
             * Format: double
             * @description Geo-radius in kilometers; zero = no geo filter
             */
            radius_km?: number;
            /**
             * Format: date-time
             * @description Last mutation timestamp (RFC3339)
             */
            updated_at?: string;
        };
        AudienceMutationBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AudienceMutationBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int32
             * @description Inclusive upper age bound in years; absent = no upper bound
             */
            age_max?: number;
            /**
             * Format: int32
             * @description Inclusive lower age bound in years; absent = no lower bound
             */
            age_min?: number;
            /**
             * Format: double
             * @description Geo-radius center latitude (WGS84); zero = no geo filter
             */
            center_lat?: number;
            /**
             * Format: double
             * @description Geo-radius center longitude (WGS84); zero = no geo filter
             */
            center_lng?: number;
            /** @description City names to include (multi); empty = any city */
            cities?: string[] | null;
            /** @description category_skill values to include (A | B | C | D | PRO); empty = any class */
            classes?: string[] | null;
            /** @description Franchise brand scope (e.g. playtennis); empty = any club */
            club_brand?: string;
            /** @description UUIDv7 club ids to scope to (multi); empty = any club */
            club_ids?: string[] | null;
            /** @description user_gender values to include (male | female | non_binary | prefer_not_say); empty = any gender */
            genders?: string[] | null;
            /** @description intent_kind values to include (sport | networking | friendship); empty = any intent */
            intents?: string[] | null;
            /** @description Human-readable audience name */
            name: string;
            /** @description Neighborhood names to include (multi); empty = any neighborhood */
            neighborhoods?: string[] | null;
            /** @description play_style values to include (casual | ranked); empty = any play style */
            play_styles?: string[] | null;
            /** @description Preferred weekdays (0=Sunday .. 6=Saturday); empty = any day */
            preferred_days?: number[] | null;
            /** @description period_of_day values to include (morning | afternoon | evening); empty = any period */
            preferred_periods?: string[] | null;
            /**
             * Format: double
             * @description Geo-radius in kilometers; zero = no geo filter
             */
            radius_km?: number;
        };
        BlockCourtSlotRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BlockCourtSlotRequestBody.json
             */
            readonly $schema?: string;
            court_id: string;
            /** Format: date-time */
            ends_at: string;
            reason: string;
            /** Format: date-time */
            starts_at: string;
        };
        BlockCourtSlotResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BlockCourtSlotResponseBody.json
             */
            readonly $schema?: string;
            court_id: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: date-time */
            starts_at: string;
            status: string;
        };
        CancellationItem: {
            booking_id: string;
            cancel_reason: string;
            /** Format: date-time */
            cancelled_at?: string;
            court_label: string;
            guest?: components["schemas"]["OpsUserRef"];
            host: components["schemas"]["OpsUserRef"];
            /** Format: double */
            hours_before?: number;
            /** @description Booking mode: casual | ranked | quick | social | event */
            match_type?: string;
            /** Format: date-time */
            starts_at: string;
            within_policy?: boolean;
        };
        CancellationsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CancellationsResponseBody.json
             */
            readonly $schema?: string;
            cancellations: components["schemas"]["CancellationItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        CountAudienceMembersBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CountAudienceMembersBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int32
             * @description Inclusive upper age bound in years; absent = no upper bound. Ignored when audience_id is set
             */
            age_max?: number;
            /**
             * Format: int32
             * @description Inclusive lower age bound in years; absent = no lower bound. Ignored when audience_id is set
             */
            age_min?: number;
            /** @description UUIDv7 of a saved audience to count; empty selects the inline filter below */
            audience_id?: string;
            /**
             * Format: double
             * @description Geo-radius center latitude (WGS84); zero = no geo filter. Ignored when audience_id is set
             */
            center_lat?: number;
            /**
             * Format: double
             * @description Geo-radius center longitude (WGS84); zero = no geo filter. Ignored when audience_id is set
             */
            center_lng?: number;
            /** @description City names to include (multi); empty = any city. Ignored when audience_id is set */
            cities?: string[] | null;
            /** @description category_skill values to include (A | B | C | D | PRO); empty = any class. Ignored when audience_id is set */
            classes?: string[] | null;
            /** @description Franchise brand scope (e.g. playtennis); empty = any club. Ignored when audience_id is set */
            club_brand?: string;
            /** @description UUIDv7 club ids to scope to (multi); empty = any club. Ignored when audience_id is set */
            club_ids?: string[] | null;
            /** @description user_gender values to include (male | female | non_binary | prefer_not_say); empty = any gender. Ignored when audience_id is set */
            genders?: string[] | null;
            /** @description intent_kind values to include (sport | networking | friendship); empty = any intent. Ignored when audience_id is set */
            intents?: string[] | null;
            /** @description Neighborhood names to include (multi); empty = any neighborhood. Ignored when audience_id is set */
            neighborhoods?: string[] | null;
            /** @description play_style values to include (casual | ranked); empty = any play style. Ignored when audience_id is set */
            play_styles?: string[] | null;
            /** @description Preferred weekdays (0=Sunday .. 6=Saturday); empty = any day. Ignored when audience_id is set */
            preferred_days?: number[] | null;
            /** @description period_of_day values to include (morning | afternoon | evening); empty = any period. Ignored when audience_id is set */
            preferred_periods?: string[] | null;
            /**
             * Format: double
             * @description Geo-radius in kilometers; zero = no geo filter. Ignored when audience_id is set
             */
            radius_km?: number;
        };
        CountAudienceMembersResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CountAudienceMembersResponseBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Number of users the filter matches (would receive the announcement)
             */
            matched: number;
            /**
             * Format: int64
             * @description Number of users excluded for having no declared skill category
             */
            missing_category: number;
        };
        CourtIssueItem: {
            affected_bookings: components["schemas"]["AffectedBookingItem"][] | null;
            /** @description Reason the founder typed when blocking the slot; absent for sync-pushed blocks (nobody typed one) */
            block_reason?: string;
            court_id: string;
            court_name: string;
            manual: boolean;
            /** Format: date-time */
            slot_end: string;
            /** Format: date-time */
            slot_start: string;
            status: string;
            street_address: string;
        };
        CourtIssuesResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CourtIssuesResponseBody.json
             */
            readonly $schema?: string;
            issues: components["schemas"]["CourtIssueItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        CourtListItem: {
            /** @description Owning franchise UUID */
            franchise_id: string;
            /** @description Franchise display name */
            franchise_name: string;
            /** @description Court UUID */
            id: string;
            /** @description Whether indoors */
            indoor: boolean;
            /** @description Whether active */
            is_active: boolean;
            /** @description Court display name */
            name: string;
            /**
             * Format: int64
             * @description Total slot count (including past)
             */
            slots_total: number;
            /** @description Surface type */
            surface: string;
        };
        CreateCourtBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateCourtBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Days of slots to generate ahead (default 90)
             */
            days_forward?: number;
            /**
             * Format: int64
             * @description Last slot start hour, inclusive, local time (default 22)
             */
            end_hour?: number;
            /** @description UUID of the owning franchise */
            franchise_id: string;
            /** @description Whether the court is indoors */
            indoor: boolean;
            /** @description Court display name */
            name: string;
            /**
             * Format: int64
             * @description Override price in cents for all slots; falls back to franchise default then ADR-0063 formula
             */
            price_cents?: number;
            /**
             * Format: int64
             * @description First slot hour, inclusive, local time (default 6)
             * @default 6
             */
            start_hour: number;
            /**
             * @description Surface type
             * @enum {string}
             */
            surface: "clay" | "hard" | "grass" | "beach" | "carpet";
        };
        CreateCourtResultBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateCourtResultBody.json
             */
            readonly $schema?: string;
            /** @description UUID of the newly created court */
            court_id: string;
            /**
             * Format: int64
             * @description Number of availability slots generated
             */
            slots_created: number;
        };
        CreateFranchiseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateFranchiseBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Default slot price in cents for courts in this franchise; falls back to the ADR-0063 formula when unset
             */
            default_price_cents?: number;
            /**
             * @description Venue kind: partner (paid club) or public (free park)
             * @enum {string}
             */
            kind: "partner" | "public";
            /** @description Display name */
            name: string;
            /** @description URL-safe slug (lowercase, hyphens) */
            slug: string;
        };
        DeleteAudienceResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteAudienceResponseBody.json
             */
            readonly $schema?: string;
            /** @description UUIDv7 of the soft-deleted audience */
            id: string;
        };
        DeletePostRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeletePostRequestBody.json
             */
            readonly $schema?: string;
            /** @description Optional reason recorded in the ops audit log */
            reason?: string;
        };
        DeletePostResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeletePostResponseBody.json
             */
            readonly $schema?: string;
            /**
             * Format: date-time
             * @description Soft-delete timestamp (RFC3339)
             */
            deleted_at: string;
            /** @description UUIDv7 of the soft-deleted post */
            post_id: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FinishedMatchItem: {
            alerts?: string[] | null;
            booking_id: string;
            court_label: string;
            currency?: string;
            /** Format: date-time */
            ends_at: string;
            guest?: components["schemas"]["OpsUserRef"];
            guest_payment?: components["schemas"]["PaymentLeg"];
            host: components["schemas"]["OpsUserRef"];
            host_payment: components["schemas"]["PaymentLeg"];
            /** @description Booking mode: casual | ranked | quick | social | event */
            match_type?: string;
            payment_settled: boolean;
            payment_status?: string;
            /** Format: int64 */
            price_cents: number;
            /** Format: date-time */
            starts_at: string;
        };
        FinishedMatchesResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FinishedMatchesResponseBody.json
             */
            readonly $schema?: string;
            matches: components["schemas"]["FinishedMatchItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        FranchiseItem: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FranchiseItem.json
             */
            readonly $schema?: string;
            /** @description Whether the franchise is currently active */
            active: boolean;
            /** @description UUIDv4 franchise identifier */
            id: string;
            /** @description Venue kind: partner | public | listing */
            kind: string;
            /** @description Display name */
            name: string;
            /** @description URL-safe unique slug (citext) */
            slug: string;
        };
        ListAllPostsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListAllPostsResponseBody.json
             */
            readonly $schema?: string;
            /** @description True when more posts exist beyond this page */
            has_more: boolean;
            /** @description Cursor for the next page; empty when no more pages */
            next_cursor?: string;
            posts: components["schemas"]["OpsPostRow"][] | null;
        };
        ListAllUsersResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListAllUsersResponseBody.json
             */
            readonly $schema?: string;
            /** @description True when more users exist beyond this page */
            has_more: boolean;
            /** @description Cursor for the next page; empty when no more pages */
            next_cursor?: string;
            users: components["schemas"]["OpsUserRow"][] | null;
        };
        ListAudiencesResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListAudiencesResponseBody.json
             */
            readonly $schema?: string;
            audiences: components["schemas"]["AudienceBody"][] | null;
        };
        ListClubsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListClubsResponseBody.json
             */
            readonly $schema?: string;
            clubs: components["schemas"]["OpsClub"][] | null;
        };
        ListCourtsBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListCourtsBody.json
             */
            readonly $schema?: string;
            courts: components["schemas"]["CourtListItem"][] | null;
        };
        ListFranchisesBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListFranchisesBody.json
             */
            readonly $schema?: string;
            franchises: components["schemas"]["FranchiseItem"][] | null;
        };
        ManualReservationItem: {
            booking_id: string;
            court_id?: string;
            /** @description court_name, else private-court bairro/rua, else street_address */
            court_label: string;
            currency?: string;
            guest?: components["schemas"]["OpsUserRef"];
            host: components["schemas"]["OpsUserRef"];
            /** @description always 'approved' for this panel */
            payment_status: string;
            /** Format: int64 */
            price_cents: number;
            /** Format: date-time */
            starts_at: string;
            /** @description franchises.street_address for the physical reservation call */
            street_address?: string;
            /** @description clay | hard | grass | beach | carpet */
            surface?: string;
        };
        ManualReservationsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ManualReservationsResponseBody.json
             */
            readonly $schema?: string;
            reservations: components["schemas"]["ManualReservationItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        OpenInviteItem: {
            /** @description UUIDv7 booking identifier */
            booking_id: string;
            /** @description Human-readable court/venue label (court_name, else private-court bairro/rua) */
            court_label: string;
            /**
             * Format: date-time
             * @description When the invite/booking was created (RFC3339)
             */
            created_at: string;
            /** @description ISO 4217 currency code (BRL) */
            currency?: string;
            /**
             * Format: date-time
             * @description Invite expiry = created_at + 2h (RFC3339); computed, not stored
             */
            expires_at: string;
            /** @description Invited guest awaiting response */
            guest: components["schemas"]["OpsUserRef"];
            /** @description Whether the guest settled their half; absent when there is no guest */
            guest_payment?: components["schemas"]["PaymentLeg"];
            /** @description Booking host/proposer who sent the invite */
            host: components["schemas"]["OpsUserRef"];
            /** @description Whether the host settled their half, and how much */
            host_payment: components["schemas"]["PaymentLeg"];
            /** @description Booking mode: casual | ranked | quick | social | event */
            match_type?: string;
            /**
             * Format: int64
             * @description Booking total in centavos; 0 for a free (public-court) booking
             */
            price_cents: number;
            /**
             * Format: date-time
             * @description Slot start time (RFC3339)
             */
            starts_at: string;
        };
        OpenInvitesResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OpenInvitesResponseBody.json
             */
            readonly $schema?: string;
            invites: components["schemas"]["OpenInviteItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        OpsClub: {
            /** @description Franchise brand (e.g. playtennis); empty for independent venues / parks */
            brand?: string;
            /** @description UUIDv7 of the club (franchises.id); the value used in audience club_ids */
            id: string;
            /** @description Human-readable club name */
            name: string;
            /** @description Neighborhood / district for display; empty when unset */
            neighborhood?: string;
        };
        OpsDossierAccount: {
            /**
             * Format: date-time
             * @description Account creation (RFC3339)
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Soft-delete timestamp; present only when status = soft_deleted
             */
            deleted_at?: string;
            /** @description Account email (users.email); staff-only contact field */
            email?: string;
            /**
             * Format: date-time
             * @description Last activity (users.last_seen_at via TouchLastSeen); último login. Empty until the user's first stamped activity.
             */
            last_seen_at?: string;
            /** @description Login phone in E.164 (users.phone_e164); staff-only contact field */
            phone_e164?: string;
            /** @description Canonical role string (e.g. consumer, staff:admin) */
            role?: string;
            /** @description active | soft_deleted | anonymized | hard_deleted | unspecified (row exists but is_active = false) */
            status: string;
        };
        OpsDossierBooking: {
            booking_id: string;
            /** @description Free-text user reason, or a system literal (guest_no_show_refund | unpaid_host_timeout). It does NOT say WHO cancelled — bookings has no cancelled_by column. */
            cancel_reason?: string;
            /** Format: date-time */
            cancelled_at?: string;
            court_label: string;
            /** Format: date-time */
            created_at?: string;
            currency?: string;
            /**
             * Format: double
             * @description Hours between the cancellation and the slot; absent when cancelled_at is unset
             */
            hours_before?: number;
            /** @description The other player; absent while the booking has no guest */
            opponent?: components["schemas"]["OpsUserRef"];
            /** @description Booking-level charge outcome; empty on legacy rows */
            payment_status?: string;
            /**
             * Format: date-time
             * @description Set by MarkPlayed; absent when the match was never played
             */
            played_at?: string;
            /**
             * Format: int64
             * @description Booking total in centavos; 0 = free (public court) booking
             */
            price_cents: number;
            /**
             * @description Which side of the booking this player is on
             * @enum {string}
             */
            role: "host" | "guest";
            /** Format: date-time */
            starts_at?: string;
            /** @description Booking lifecycle status */
            status: string;
            /** @description This player's payment leg (host_has_paid/host_paid, or guest_has_paid/guest_paid) */
            their_leg: components["schemas"]["PaymentLeg"];
        };
        OpsDossierProfile: {
            bio?: string;
            /** @description Skill category A|B|C|D|PRO; empty until nivelamento */
            category?: string;
            /** @description Self-declared category at onboarding */
            category_declared?: string;
            city?: string;
            /** Format: date-time */
            created_at?: string;
            /** @description profiles.display_name; empty when onboarding never completed */
            display_name?: string;
            neighborhood?: string;
            /** @description casual | ranked */
            play_style?: string;
            /** @description True when the player hosts on their own private court */
            plays_at_home: boolean;
            /** @description tennis | padel | beach_tennis */
            sport?: string;
            state?: string;
            verified_badges?: string[] | null;
            /**
             * Format: int32
             * @description Gamification level (profiles.xp_level)
             */
            xp_level?: number;
        };
        OpsDossierRatings: {
            /**
             * Format: double
             * @description Mean of the ratings received; absent when count = 0
             */
            avg_rating?: number;
            /**
             * Format: int32
             * @description Number of ratings this player received
             */
            count: number;
            /** @description Each individual rating with its author, newest first */
            ratings: components["schemas"]["PlayerRatingItem"][] | null;
        };
        OpsDossierStats: {
            /** Format: int32 */
            as_guest: number;
            /** Format: int32 */
            as_host: number;
            /**
             * Format: int32
             * @description Every booking this player is on (host + guest), complete
             */
            bookings_total: number;
            /**
             * Format: int32
             * @description Cancelled bookings this player was on — by EITHER side or the system; not attributable (no cancelled_by column)
             */
            cancelled: number;
            /**
             * Format: int32
             * @description Cancelled bookings with no cancelled_at — the lead time cannot be computed, so they are NOT in cancelled_within_48h
             */
            cancelled_lead_time_unknown: number;
            /**
             * Format: int32
             * @description Of those, cancelled less than 48h before the slot (the beta policy window). Again not attributable to a side.
             */
            cancelled_within_48h: number;
            /**
             * Format: int32
             * @description Bookings with played_at set (MarkPlayed ran)
             */
            matches_played: number;
            /**
             * Format: int32
             * @description Bookings in status no_show
             */
            no_shows: number;
            /**
             * Format: int32
             * @description Live (non-cancelled, non-refunded) paid bookings where THIS player's leg is still unsettled
             */
            unpaid_legs: number;
        };
        OpsPostAuthor: {
            /** @description URL of the author's first profile photo; empty when none */
            avatar_url?: string;
            /** @description Display name (profiles.display_name, else @username, else short id) */
            name: string;
            /** @description UUIDv7 of the author */
            user_id: string;
            /** @description users.username; absent when never set */
            username?: string;
        };
        OpsPostRow: {
            /** @description 1-2 author UUIDv7s (2 for co-authored score posts) */
            author_ids: string[] | null;
            /** @description Display identity for each author id, best-effort via user-service */
            authors: components["schemas"]["OpsPostAuthor"][] | null;
            caption?: string;
            /** Format: int32 */
            comments_count: number;
            /** Format: date-time */
            created_at?: string;
            /**
             * Format: date-time
             * @description Soft-delete timestamp; absent when the post is live
             */
            deleted_at?: string;
            /** @description UUIDv7 of the post */
            id: string;
            /** Format: int32 */
            likes_count: number;
            /** @description CDN URLs of attached photos */
            photo_urls?: string[] | null;
            /** @description photo | score | match | general | unspecified */
            post_type: string;
            /** @description True when an open (pending/reviewing) report targets this post */
            reported: boolean;
            /** @description Structured score payload (canonical posts.score_json); absent for non-score posts */
            score_json?: unknown;
        };
        OpsSearchBooking: {
            /** @description UUIDv7 booking identifier */
            booking_id: string;
            /** @description Human-readable court/venue label */
            court_label: string;
            /** @description ISO 4217 currency code (BRL) */
            currency?: string;
            /** @description Invited/confirmed guest; absent when the booking has none */
            guest?: components["schemas"]["OpsUserRef"];
            /** @description Booking host; name joined from user-service */
            host: components["schemas"]["OpsUserRef"];
            /** @description PIX/card payment outcome; empty on legacy rows */
            payment_status?: string;
            /**
             * Format: int64
             * @description Booking total in centavos; 0 for a free booking
             */
            price_cents: number;
            /**
             * Format: date-time
             * @description Slot start (RFC3339)
             */
            starts_at?: string;
            /** @description Booking lifecycle status */
            status: string;
        };
        OpsSearchResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OpsSearchResponseBody.json
             */
            readonly $schema?: string;
            /** @description True when user-service has further pages for this query. Always false for a UUID lookup. */
            has_more: boolean;
            /** @description The (trimmed) query that was executed */
            query: string;
            results: components["schemas"]["OpsSearchResult"][] | null;
        };
        OpsSearchResult: {
            booking?: components["schemas"]["OpsSearchBooking"];
            /**
             * @description Which payload is populated
             * @enum {string}
             */
            kind: "user" | "booking";
            /**
             * @description How the row was matched
             * @enum {string}
             */
            matched_by: "trgm_search" | "user_id" | "booking_id";
            user?: components["schemas"]["OpsSearchUser"];
        };
        OpsSearchUser: {
            /**
             * Format: date-time
             * @description When the account was created (RFC3339)
             */
            created_at?: string;
            /** @description Display name resolved from user-service (display_name, else @username, else short id) */
            name: string;
            /** @description Account status: active | soft_deleted | anonymized | hard_deleted | unspecified (inactive) */
            status?: string;
            /** @description UUIDv7 of the user */
            user_id: string;
            /** @description users.username; absent when the player never set one */
            username?: string;
        };
        OpsUserDossierResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OpsUserDossierResponseBody.json
             */
            readonly $schema?: string;
            account: components["schemas"]["OpsDossierAccount"];
            /** @description Their bookings (host + guest side), newest slot first */
            bookings: components["schemas"]["OpsDossierBooking"][] | null;
            /** @description True when the booking list hit the 100-row cap and is therefore incomplete */
            bookings_truncated: boolean;
            /** @description Absent when the user row exists but no profile row does (onboarding abandoned) */
            profile?: components["schemas"]["OpsDossierProfile"];
            ratings_received: components["schemas"]["OpsDossierRatings"];
            stats?: components["schemas"]["OpsDossierStats"];
            /** @description Why stats is absent, when it is */
            stats_unavailable_reason?: string;
            /** @description The player, with the same resolved-name discipline as every other panel */
            user: components["schemas"]["OpsUserRef"];
        };
        OpsUserRef: {
            /** @description Account email (users.email); staff-only, only on contact-enriched panels */
            email?: string;
            /** @description Display name resolved from user-service (profiles.display_name) */
            name: string;
            /** @description Login phone E.164 (users.phone_e164); staff-only, empty until PhoneSync backfills it */
            phone?: string;
            /** @description UUIDv7 of the user */
            user_id: string;
        };
        OpsUserRow: {
            /** @description URL of the first profile photo; empty when none */
            avatar_url?: string;
            /**
             * Format: int32
             * @description Always 0 — no cheap per-user count RPC exists; best-effort, see the user dossier for real per-user rollups
             */
            bookings_count: number;
            /**
             * Format: date-time
             * @description Account creation (RFC3339)
             */
            created_at?: string;
            /** @description users.email (staff-only contact field) */
            email?: string;
            /** @description UUIDv7 of the user */
            id: string;
            /**
             * Format: date-time
             * @description Last activity (users.last_seen_at); empty until first stamped activity
             */
            last_seen_at?: string;
            /** @description Skill category A|B|C|D|PRO (profiles.category); empty until nivelamento */
            level?: string;
            /** @description Display name resolved from profiles.display_name, else @username, else short id */
            name: string;
            /** @description Login phone in E.164 (users.phone_e164); staff-only */
            phone_e164?: string;
            /**
             * Format: int32
             * @description Always 0 — no cheap per-user count RPC exists; best-effort, see the user dossier for real per-user rollups
             */
            posts_count: number;
            /** @description users.username; absent when never set */
            username?: string;
            /**
             * Format: int32
             * @description Gamification level (profiles.xp_level); 0 when the user has no profile
             */
            xp_level: number;
        };
        PaymentIssueItem: {
            /**
             * Format: int64
             * @description Charged amount in centavos (booking total_cents)
             */
            amount_cents: number;
            /** @description UUIDv7 booking identifier */
            booking_id: string;
            /** @description Booking lifecycle status at the time of the issue */
            booking_status: string;
            /**
             * Format: date-time
             * @description When the booking was created (RFC3339)
             */
            created_at: string;
            /** @description ISO 4217 currency code (BRL) */
            currency: string;
            /** @description PIX payment outcome: pending | rejected */
            payment_status: string;
            /** @description The payer (booking host); name joined from user-service on user_id */
            user: components["schemas"]["OpsUserRef"];
        };
        PaymentIssuesResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PaymentIssuesResponseBody.json
             */
            readonly $schema?: string;
            issues: components["schemas"]["PaymentIssueItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        PaymentLeg: {
            /** Format: int64 */
            amount_cents: number;
            currency?: string;
            paid: boolean;
        };
        PlayerEvaluationItem: {
            /**
             * Format: double
             * @description Mean of all ratings this player received (0 when none)
             */
            avg_rating: number;
            /**
             * Format: int32
             * @description Number of ratings this player received
             */
            count: number;
            /** @description The rated player; name joined from user-service */
            player: components["schemas"]["OpsUserRef"];
            /** @description Each individual rating with its author, newest first */
            ratings: components["schemas"]["PlayerRatingItem"][] | null;
        };
        PlayerEvaluationsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PlayerEvaluationsResponseBody.json
             */
            readonly $schema?: string;
            players: components["schemas"]["PlayerEvaluationItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        PlayerRatingItem: {
            /** @description The player who left this rating */
            author: components["schemas"]["OpsUserRef"];
            /** @description Optional free-text comment */
            comment?: string;
            /**
             * Format: date-time
             * @description When the rating was left (RFC3339)
             */
            created_at: string;
            /**
             * Format: int32
             * @description Overall rating 1..5
             */
            rating: number;
            /** @description Preset tags (e.g. court_quality:8, opponent_level:same, opponent_conduct:9) */
            tags?: string[] | null;
        };
        PostReportItem: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PostReportItem.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            details: string;
            post_id: string;
            reason: string;
            report_id: string;
            reported_user: components["schemas"]["OpsUserRef"];
            reporter: components["schemas"]["OpsUserRef"];
            /** Format: date-time */
            resolved_at?: string;
            resolved_by?: string;
            status: string;
        };
        ReportsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReportsResponseBody.json
             */
            readonly $schema?: string;
            reports: components["schemas"]["PostReportItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        SendAnnouncementRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SendAnnouncementRequestBody.json
             */
            readonly $schema?: string;
            /** @description Saved audience UUIDv7 to target; empty broadcasts to all PlayTennis members (legacy default) */
            audience_id?: string;
            /** @description Push + inbox notification body text */
            body: string;
            /** @description Deep link routed on tap; defaults to lits://feed when empty */
            deep_link?: string;
            /** @description Push + inbox notification title */
            title: string;
        };
        SendAnnouncementResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SendAnnouncementResponseBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Members whose Send failed (counted, not fatal to the broadcast)
             */
            failed: number;
            /**
             * Format: int64
             * @description Members the notification was successfully dispatched to
             */
            sent: number;
            /**
             * Format: int64
             * @description Total members targeted (audience members, or all PlayTennis members on the legacy default)
             */
            total: number;
        };
        UpcomingMatchItem: {
            alerts?: string[] | null;
            booking_id: string;
            court_label: string;
            /** Format: date-time */
            created_at: string;
            currency?: string;
            /** Format: date-time */
            ends_at: string;
            guest?: components["schemas"]["OpsUserRef"];
            guest_payment?: components["schemas"]["PaymentLeg"];
            host: components["schemas"]["OpsUserRef"];
            host_payment: components["schemas"]["PaymentLeg"];
            /** @description Booking mode: casual | ranked | quick | social | event */
            match_type?: string;
            payment_settled: boolean;
            payment_status?: string;
            /** Format: int64 */
            price_cents: number;
            /** Format: date-time */
            starts_at: string;
        };
        UpcomingMatchesResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpcomingMatchesResponseBody.json
             */
            readonly $schema?: string;
            matches: components["schemas"]["UpcomingMatchItem"][] | null;
            /** Format: int32 */
            total: number;
        };
        UpdateReportStatusRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateReportStatusRequestBody.json
             */
            readonly $schema?: string;
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "ops-send-announcement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SendAnnouncementRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendAnnouncementResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-audiences": {
        parameters: {
            query?: {
                /** @description Include soft-deleted audiences (default false) */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAudiencesResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-create-audience": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AudienceMutationBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudienceBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-count-audience-members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CountAudienceMembersBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountAudienceMembersResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-update-audience": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the audience to update */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AudienceMutationBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudienceBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-delete-audience": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the audience to soft-delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteAudienceResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-cancellations": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancellationsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-search-clubs": {
        parameters: {
            query?: {
                /** @description Case-insensitive substring filter over club name; empty returns the first clubs up to limit */
                q?: string;
                /** @description Max clubs to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListClubsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-block-court-slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BlockCourtSlotRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockCourtSlotResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-court-issues": {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourtIssuesResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-courts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCourtsBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-create-court": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateCourtBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCourtResultBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-delete-court": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Court UUID to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-finished-matches": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinishedMatchesResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-franchises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFranchisesBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-create-franchise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateFranchiseBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FranchiseItem"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-manual-reservations": {
        parameters: {
            query?: {
                /** @description Max rows to return */
                limit?: number;
                /** @description Rows to skip (paging) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualReservationsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-open-invites": {
        parameters: {
            query?: {
                /** @description Max rows to return */
                limit?: number;
                /** @description Rows to skip (paging) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenInvitesResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-payment-issues": {
        parameters: {
            query?: {
                /** @description Max rows to return */
                limit?: number;
                /** @description Rows to skip (paging) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIssuesResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-player-evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerEvaluationsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-posts": {
        parameters: {
            query?: {
                /** @description Optional caption search (ILIKE). Empty returns all posts. */
                q?: string;
                /** @description Opaque keyset cursor from a previous page's next_cursor */
                cursor?: string;
                /** @description Max rows to return */
                limit?: number;
                /** @description Include soft-deleted posts (default false) */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAllPostsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-delete-post": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the post to soft-delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeletePostRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletePostResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-reports": {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-update-report-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateReportStatusRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostReportItem"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-search": {
        parameters: {
            query: {
                /** @description Free-text query (pg_trgm over display_name + username), or a UUID to resolve as a user id / booking id */
                q: string;
                /** @description Max player hits to return (user-service clamps at 50). Ignored for a UUID lookup. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsSearchResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-upcoming-matches": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingMatchesResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-list-users": {
        parameters: {
            query?: {
                /** @description Optional filter over name/username/email/phone (ILIKE). Empty returns all users. */
                q?: string;
                /** @description Opaque keyset cursor from a previous page's next_cursor */
                cursor?: string;
                /** @description Max rows to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAllUsersResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ops-get-user-dossier": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the player */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsUserDossierResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
